[package]
name = "embedded-hal-fuzz"
version = "0.1.2"
edition = "2021"
authors = ["Nathaniel Brough"]
repository = "https://github.com/silvergasp/embedded-hal-fuzz"
description = "Fuzzing backends for embedded_hal"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = {version = "0.2.7", features = ["unproven"]}
nb = "1.0.0"

[dev-dependencies]
num-traits = "0.2"
num-derive = "0.3"
libfuzzer-sys = "0.4"

[package.metadata.commits]
defaults = true